# -*- coding: utf-8 -*-
"""Tabela de tradução — parte A. Ver tools/traduzir.py."""

T = {
"a11y.skip": ("Skip to content", "Gå til innholdet", "Ir al contenido"),
"casa.medida": ("Bespoke", "Skreddersydd", "A medida"),
"casa.plataformas": ("Own platforms", "Egne plattformer", "Plataformas propias"),
"cont.c1": ("Email", "E-post", "Correo"),
"cont.c2": ("Registration", "Registrering", "Registro"),
"cont.c3": ("Languages", "Språk", "Idiomas"),
"cont.c5": ("Address", "Adresse", "Dirección"),
"cont.c4": ("Response", "Svar", "Respuesta"),
"cont.c4.v": ("Within 2 business days", "Innen 2 virkedager", "Hasta 2 días hábiles"),
"cont.card.titulo": ("Channels", "Kanaler", "Canales"),
"cont.eyebrow": ("Contact", "Kontakt", "Contacto"),
"cont.lead": (
  "The more concrete the context, the more useful the answer. Select the platform or service you are interested in and describe the situation — we reply with scope, format and timeline within two business days.",
  "Jo mer konkret konteksten er, desto nyttigere blir svaret. Velg plattformen eller tjenesten du er interessert i og beskriv situasjonen — vi svarer med omfang, format og tidsplan innen to virkedager.",
  "Cuanto más concreto sea el contexto, más útil será la respuesta. Seleccione la plataforma o el servicio de interés y describa la situación — respondemos con alcance, formato y plazo en hasta dos días hábiles."),
"cont.rec.corpo": (
  "Complaints about ongoing or completed work come through this same form, with the word «complaint» at the start of the message. They are logged, handled against a deadline and answered in writing.",
  "Klager på pågående eller fullført arbeid sendes gjennom det samme skjemaet, med ordet «klage» først i meldingen. De registreres, behandles med frist og besvares skriftlig.",
  "Las reclamaciones sobre trabajos en curso o concluidos entran por el mismo formulario, con la palabra «reclamación» al inicio del mensaje. Se registran, se tratan con plazo y se responden por escrito."),
"cont.rec.link": ("See the full procedure", "Se hele prosedyren", "Ver el procedimiento completo"),
"cont.rec.titulo": ("Complaints", "Klager", "Reclamaciones"),
"cont.seg.corpo": (
  "Found a security flaw? The responsible disclosure channel is declared at <span class=\"mono\">/.well-known/security.txt</span>, per RFC 9116.",
  "Funnet et sikkerhetshull? Kanalen for ansvarlig varsling er oppgitt i <span class=\"mono\">/.well-known/security.txt</span>, i tråd med RFC 9116.",
  "¿Encontró una falla de seguridad? El canal de divulgación responsable está declarado en <span class=\"mono\">/.well-known/security.txt</span>, conforme a la RFC 9116."),
"cont.seg.titulo": ("Security", "Sikkerhet", "Seguridad"),
"cont.titulo": ("Describe the problem.", "Beskriv problemet.", "Describa el problema."),
"cook.eyebrow": ("Legal document", "Juridisk dokument", "Documento legal"),
"cook.lead": (
  "This site stores very little in your browser, and nothing non-essential without your prior authorisation. This page lists it item by item.",
  "Dette nettstedet lagrer svært lite i nettleseren din, og ingenting ikke-essensielt uten ditt forhåndssamtykke. Denne siden lister opp alt, punkt for punkt.",
  "Este sitio guarda muy poco en su navegador, y nada que no sea esencial sin su autorización previa. Esta página lo detalla punto por punto."),
"cook.titulo": ("Cookie Notice", "Informasjonskapsler", "Aviso de Cookies"),
"cookie.aceitar": ("Accept all", "Godta alle", "Aceptar todos"),
"cookie.analiticos": ("Analytics", "Analyse", "Analíticos"),
"cookie.essenciais": ("Essential (always on)", "Nødvendige (alltid på)", "Esenciales (siempre activos)"),
"cookie.marketing": ("Marketing", "Markedsføring", "Marketing"),
"cookie.recusar": ("Essential only", "Kun nødvendige", "Solo esenciales"),
"cookie.salvar": ("Save choice", "Lagre valg", "Guardar elección"),
"cookie.texto": (
  "We use essential cookies for the site to work. Everything else is only activated with your authorisation.",
  "Vi bruker nødvendige informasjonskapsler for at nettstedet skal fungere. Alt annet aktiveres kun med ditt samtykke.",
  "Usamos cookies esenciales para el funcionamiento del sitio. Los demás solo se activan con su autorización."),
"cta.btn": ("Open the form", "Åpne skjemaet", "Abrir formulario"),
"cta.eyebrow": ("Contact", "Kontakt", "Contacto"),
"cta.lead": (
  "Portuguese, English, Norwegian and Spanish. Reply within two business days.",
  "Portugisisk, engelsk, norsk og spansk. Svar innen to virkedager.",
  "Portugués, inglés, noruego y español. Respuesta en hasta dos días hábiles."),
"cta.titulo": (
  "Describe the problem. We answer with scope and timeline.",
  "Beskriv problemet. Vi svarer med omfang og tidsplan.",
  "Describa el problema. Respondemos con alcance y plazo."),
"disco.btn": ("Open the interactive disc", "Åpne den interaktive skiven", "Abrir el disco interactivo"),
"disco.chamada": (
  "Five fronts and twenty-six items across platforms and services. In the interactive disc each slice opens the list, and each item shows what it includes and how it is contracted.",
  "Fem arbeidsområder og tjueseks punkter fordelt på plattformer og tjenester. I den interaktive skiven åpner hver sektor listen, og hvert punkt viser hva det omfatter og hvordan det avtales.",
  "Cinco frentes y veintiséis ítems entre plataformas y servicios. En el disco interactivo cada porción abre la lista, y cada ítem muestra qué incluye y cómo se contrata."),
"disco.eyebrow": ("Catalogue", "Katalog", "Catálogo"),
"disco.hub.corpo": ("Digital Solutions · Norway", "Digital Solutions · Norge", "Digital Solutions · Noruega"),
"disco.hub.kicker": ("Choose a slice", "Velg en sektor", "Elija una porción"),
"disco.hub.titulo": ("Platforms & Services", "Plattformer og tjenester", "Plataformas y Servicios"),
"disco.lead": (
  "Each slice is a line of work. The outer ring separates what is a licensed product from what is built per project.",
  "Hver sektor er et arbeidsområde. Den ytre ringen skiller lisensiert produkt fra det som bygges per prosjekt.",
  "Cada porción es una línea de trabajo. El aro externo separa lo que es producto licenciado de lo que se construye por proyecto."),
"disco.titulo": (
  "Five fronts, two families, one disc",
  "Fem arbeidsområder, to familier, én skive",
  "Cinco frentes, dos familias, un disco"),
"disco.vazio": (
  "Select a slice of the disc to see the platforms and services in that front.",
  "Velg en sektor i skiven for å se plattformene og tjenestene i det arbeidsområdet.",
  "Seleccione una porción del disco para ver las plataformas y servicios de ese frente."),
"doc.catalogo": ("Catalogue", "Katalog", "Catálogo"),
"doc.idioma": ("Master language", "Kildespråk", "Idioma maestro"),
"e404.b1": ("Back to home", "Tilbake til forsiden", "Volver al inicio"),
"e404.b2": ("See the catalogue", "Se katalogen", "Ver el catálogo"),
"e404.b3": ("Talk to Digital Solutions", "Kontakt Digital Solutions", "Hablar con Digital Solutions"),
"e404.lead": (
  "The link may have changed, or the address may have been typed differently. The paths below lead somewhere.",
  "Lenken kan ha endret seg, eller adressen kan være skrevet annerledes. Veiene nedenfor fører et sted.",
  "El enlace puede haber cambiado o la dirección puede haberse escrito de otra forma. Las rutas de abajo llevan a algún lugar."),
"e404.titulo": ("This address does not exist.", "Denne adressen finnes ikke.", "Esta dirección no existe."),
"footer.col.frentes": ("Fronts", "Arbeidsområder", "Frentes"),
"footer.col.institucional": ("Corporate", "Selskapet", "Institucional"),
"footer.col.plataformas": ("Platforms", "Plattformer", "Plataformas"),
"footer.desc": (
  "Own platforms and bespoke systems, built in Norway to run in any time zone.",
  "Egne plattformer og skreddersydde systemer, bygget i Norge for drift i enhver tidssone.",
  "Plataformas propias y sistemas a medida, construidos en Noruega para operar en cualquier huso horario."),
"footer.i1": ("About the company", "Om selskapet", "Sobre la empresa"),
"footer.i2": ("Compliance and quality", "Samsvar og kvalitet", "Conformidad y calidad"),
"footer.i3": ("Contact and proposals", "Kontakt og tilbud", "Contacto y propuestas"),
"footer.i4": ("Privacy Policy", "Personvernerklæring", "Política de Privacidad"),
"footer.i5": ("Terms of Use", "Bruksvilkår", "Términos de Uso"),
"footer.i6": ("Cookie Notice", "Informasjonskapsler", "Aviso de Cookies"),
"footer.rights": ("All rights reserved", "Alle rettigheter forbeholdt", "Todos los derechos reservados"),
"footer.s1": ("AI", "KI", "IA"),
"footer.s2": ("B2B", "B2B", "B2B"),
"footer.s3": ("Biomechanical Prevention", "Biomekanisk forebygging", "Prevención Biomecánica"),
"footer.s4": ("CRM and Extranet", "CRM og ekstranett", "CRM y Extranet"),
"footer.s5": ("Development and Data", "Utvikling og data", "Desarrollo y Datos"),
"form.email": ("Email *", "E-post *", "Correo *"),
"form.empresa": ("Company", "Selskap", "Empresa"),
"form.enviar": ("Send message", "Send melding", "Enviar mensaje"),
"form.lgpd": (
  "I authorise the processing of the data above in order to answer this request, in accordance with the Privacy Policy. The data is not shared with third parties for commercial purposes.",
  "Jeg samtykker til behandling av opplysningene ovenfor for å besvare denne henvendelsen, i samsvar med personvernerklæringen. Opplysningene deles ikke med tredjeparter for kommersielle formål.",
  "Autorizo el tratamiento de los datos anteriores para responder a esta solicitud, conforme a la Política de Privacidad. Los datos no se comparten con terceros con fines comerciales."),
"form.mensagem": ("Situation and need *", "Situasjon og behov *", "Situación y necesidad *"),
"form.mensagem.ph": (
  "What needs solving, what has already been tried, and what will decide whether the work succeeded.",
  "Hva som må løses, hva som allerede er forsøkt, og hva som avgjør om arbeidet lykkes.",
  "Qué necesita resolverse, qué se ha intentado ya y qué decide el éxito del trabajo."),
"form.nome": ("Name *", "Navn *", "Nombre *"),
"form.pais": ("Country of operation", "Driftsland", "País de la operación"),
"form.pais.outro": ("Other", "Annet", "Otro"),
"form.prazo": ("Intended timeline", "Ønsket tidsramme", "Plazo previsto"),
"form.prazo.1": ("Immediate", "Umiddelbart", "Inmediato"),
"form.prazo.2": ("Within 3 months", "Innen 3 måneder", "Hasta 3 meses"),
"form.prazo.3": ("Within 6 months", "Innen 6 måneder", "Hasta 6 meses"),
"form.prazo.4": ("Still assessing", "Fortsatt under vurdering", "Aún evaluando"),
"form.servico": ("Platform or service", "Plattform eller tjeneste", "Plataforma o servicio"),
"form.servico.hint": (
  "If you are not sure where it fits, leave it blank and describe it below.",
  "Er du usikker på hvor det hører hjemme, la feltet stå tomt og beskriv det nedenfor.",
  "Si no sabe dónde encaja, déjelo en blanco y descríbalo abajo."),
"form.servico.vazio": (
  "Select — the list follows the catalogue disc",
  "Velg — listen følger katalogskiven",
  "Seleccione — la lista sigue el disco del catálogo"),
"form.telefone": ("Phone", "Telefon", "Teléfono"),
"frentes.1.corpo": (
  "Corporate AI platform that produces the everyday deliverables: project plan, spreadsheet, presentation, financial analysis, content. Multilingual, with history kept in the company's own base.",
  "KI-plattform for virksomheten som produserer de daglige leveransene: prosjektplan, regneark, presentasjon, finansanalyse, innhold. Flerspråklig, med historikk lagret i selskapets egen base.",
  "Plataforma de IA corporativa que produce las entregas del día a día: proyecto, hoja de cálculo, presentación, análisis financiero, contenido. Multilingüe, con historial en la base de la propia empresa."),
"frentes.1.titulo": ("MIMBAI AI with Claude", "MIMBAI KI med Claude", "IA MIMBAI con Claude"),
"frentes.2.corpo": (
  "Business network with AI matching across Europe, Brazil, China and the Nordics. Profile analysed, fit score and a formal introduction between the parties.",
  "Forretningsnettverk med KI-basert matching mellom Europa, Brasil, Kina og Norden. Profilen analyseres, du får en treffscore og en formell introduksjon mellom partene.",
  "Red de negocios con matching por IA entre Europa, Brasil, China y los países nórdicos. Perfil analizado, score de afinidad e introducción formal entre las partes."),
"frentes.2.titulo": ("B2B MIMBAI · Oslo Meet", "B2B MIMBAI · Oslo Meet", "B2B MIMBAI · Oslo Meet"),
"frentes.3.corpo": (
  "Real-time biomechanical risk index for transport and logistics. Lumbar compression, surface factor, vibration per ISO 2631-1 and fatigue accumulated over the shift.",
  "Biomekanisk risikoindeks i sanntid for transport og logistikk. Lumbal kompresjon, underlagsfaktor, vibrasjon etter ISO 2631-1 og akkumulert utmattelse gjennom skiftet.",
  "Índice de riesgo biomecánico en tiempo real para transporte y logística. Compresión lumbar, factor de superficie, vibración según ISO 2631-1 y fatiga acumulada en la jornada."),
"frentes.3.titulo": ("SALA · Safe-Load Analytics", "SALA · Safe-Load Analytics", "SALA · Safe-Load Analytics"),
"frentes.4.corpo": (
  "Sales pipeline, customer base and support tickets in one panel, with an external area where the client follows contract, documents and deliveries.",
  "Salgstrakt, kundebase og saker i samme panel, med et eksternt område der kunden følger kontrakt, dokumenter og leveranser.",
  "Embudo de ventas, base de clientes y tickets en el mismo panel, con área externa para que el cliente siga contrato, documentos y entregas."),
"frentes.4.titulo": ("CRM & Extranet", "CRM og ekstranett", "CRM y Extranet"),
"frentes.5.corpo": (
  "Web applications, proprietary algorithms, process automation and data engineering in Python. Documentation and knowledge transfer are part of the delivery.",
  "Webapplikasjoner, egne algoritmer, prosessautomatisering og datateknikk i Python. Dokumentasjon og kunnskapsoverføring inngår i leveransen.",
  "Aplicaciones web, algoritmos propios, automatización de procesos e ingeniería de datos en Python. La documentación y la transferencia de conocimiento forman parte de la entrega."),
"frentes.5.titulo": ("Development & Data", "Utvikling og data", "Desarrollo y Datos"),
"frentes.6.corpo": (
  "When a project calls for a reading of the operation or a regulatory opinion, Digital Solutions delivers the technical part together with Barros Consultoria and Inteligência Sanitária. Each item's record states who delivers what.",
  "Når et prosjekt krever forståelse av driften eller en regulatorisk vurdering, leverer Digital Solutions den tekniske delen sammen med Barros Consultoria og Inteligência Sanitária. Hvert punkt i katalogen oppgir hvem som leverer hva.",
  "Cuando el proyecto exige lectura de la operación o dictamen regulatorio, Digital Solutions ejecuta la parte técnica junto con Barros Consultoria e Inteligência Sanitária. La ficha de cada ítem indica quién entrega qué."),
"frentes.6.eyebrow": ("Integration", "Samspill", "Integración"),
"frentes.6.titulo": ("Working together", "Samarbeid", "Trabajo conjunto"),
"frentes.eyebrow": ("Fronts", "Arbeidsområder", "Frentes"),
"frentes.titulo": (
  "What Digital Solutions delivers",
  "Hva Digital Solutions leverer",
  "Lo que entrega Digital Solutions"),
"hero.cta1": ("See the catalogue", "Se katalogen", "Ver el catálogo"),
"hero.cta2": ("Request a proposal", "Be om tilbud", "Pedir una propuesta"),
"hero.eyebrow": ("Norway · org.nr 996 041 468", "Norge · org.nr 996 041 468", "Noruega · org.nr 996 041 468"),
"hero.lead": (
  "Digital Solutions builds its own platforms and bespoke systems. Five lines of work, documented item by item, with what each one includes and how it is contracted.",
  "Digital Solutions bygger egne plattformer og skreddersydde systemer. Fem arbeidsområder, dokumentert punkt for punkt, med hva hvert enkelt omfatter og hvordan det avtales.",
  "Digital Solutions construye plataformas propias y sistemas a medida. Cinco frentes de trabajo, documentados ítem por ítem, con lo que incluye cada uno y en qué formato se contrata."),
"hero.titulo": (
  "Software the company uses every day, without depending on whoever wrote it.",
  "Programvare selskapet bruker hver dag, uten å være avhengig av den som skrev den.",
  "Software que la empresa usa todos los días, sin depender de quien lo escribió."),
"metodo.1.d": (
  "A proposal with named deliverables, acceptance criteria and what is out of scope. Nothing starts before that is agreed in writing.",
  "Et tilbud med navngitte leveranser, akseptkriterier og hva som faller utenfor omfanget. Ingenting starter før dette er skriftlig avtalt.",
  "Propuesta con entregables nombrados, criterios de aceptación y lo que queda fuera del alcance. Nada empieza sin eso acordado por escrito."),
"metodo.1.t": ("Scope", "Omfang", "Alcance"),
"metodo.2.d": (
  "Milestones with dates, a named owner and status meetings at an agreed rhythm. Deviation is reported when it appears, not at closing.",
  "Milepæler med dato, navngitt ansvarlig og statusmøter i avtalt rytme. Avvik meldes når de oppstår, ikke ved avslutning.",
  "Hitos con fecha, responsable nominal y reunión de estado con la periodicidad acordada. La desviación se comunica cuando aparece, no al cierre."),
"metodo.2.t": ("Execution", "Gjennomføring", "Ejecución"),
"metodo.3.d": (
  "Every deliverable is checked against the acceptance criteria before it reaches the client. The check itself is recorded.",
  "Hver leveranse kontrolleres mot akseptkriteriene før den går til kunden. Kontrollen registreres.",
  "Cada entregable pasa por verificación contra los criterios de aceptación antes de llegar al cliente. La verificación queda registrada."),
"metodo.3.t": ("Verification", "Verifisering", "Verificación"),
"metodo.4.d": (
  "Version control in a repository, a staging environment separate from production, and a backup routine declared in the contract.",
  "Versjonskontroll i repositorium, testmiljø atskilt fra produksjon, og sikkerhetskopiering med frekvens oppgitt i kontrakten.",
  "Versionado en repositorio, entorno de homologación separado del de producción y rutina de copia de seguridad declarada en contrato."),
"metodo.4.t": ("Code and data", "Kode og data", "Código y datos"),
"metodo.5.d": (
  "Documented handover, knowledge transfer to the client's team and a record of lessons learned.",
  "Dokumentert overlevering, kunnskapsoverføring til kundens team og registrering av erfaringer.",
  "Entrega documentada, transferencia de conocimiento al equipo del cliente y registro de lecciones aprendidas."),
"metodo.5.t": ("Closing", "Avslutning", "Cierre"),
"metodo.cta": ("See the compliance page", "Se samsvarssiden", "Ver la página de conformidad"),
"metodo.eyebrow": ("How we work", "Slik jobber vi", "Cómo trabajamos"),
"metodo.lead": (
  "The method follows the logic of a quality management system: what was agreed is written down, what was done is recorded, and what went wrong becomes a corrective action with a deadline.",
  "Metoden følger logikken i et kvalitetsstyringssystem: det som avtales blir skrevet ned, det som gjøres blir registrert, og det som går galt blir en korrigerende tiltak med frist.",
  "El método sigue la lógica de un sistema de gestión de la calidad: lo acordado queda escrito, lo hecho queda registrado, y lo que salió mal se convierte en acción correctiva con plazo."),
"metodo.titulo": (
  "Every delivery has an owner, a deadline and a record",
  "Hver leveranse har en ansvarlig, en frist og et spor",
  "Toda entrega tiene responsable, plazo y registro"),
"nav.contato": ("Contact", "Kontakt", "Contacto"),
"nav.inicio": ("Home", "Hjem", "Inicio"),
"nav.qualidade": ("Compliance", "Samsvar", "Conformidad"),
"nav.servicos": ("Services", "Tjenester", "Servicios"),
"nav.sobre": ("About", "Om oss", "Sobre"),
"priv.eyebrow": ("Legal document", "Juridisk dokument", "Documento legal"),
"priv.lead": (
  "This policy describes which personal data dsnorge.com collects, for what, for how long, and what you may demand about it.",
  "Denne erklæringen beskriver hvilke personopplysninger dsnorge.com samler inn, til hva, hvor lenge, og hva du kan kreve om dem.",
  "Esta política describe qué datos personales recoge dsnorge.com, para qué, durante cuánto tiempo y qué puede exigir usted al respecto."),
"priv.titulo": ("Privacy Policy", "Personvernerklæring", "Política de Privacidad"),
}
